
name: 'MyfirstPipeline'

on: 
  push:
    branches:
      - 'main'
      - 'feature/**'
permissions:
  id-token: write
  contents: read      
jobs:
  terraformInit:
    name: terraform initwa
    runs-on: ubuntu-latest
    steps:
    - name: kuchbhi
      run: echo Hello amit
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: Install Terraform
      uses: little-core-labs/install-terraform@v2.0.0
      with:
        version: 1.13.0
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Terraform Init
      id: init
      run: terraform init -input=false   
      working-directory: .
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
      continue-on-error: true 
      working-directory: .
    - name: Terraform Apply
      id: Apply
      run: terraform apply --auto-approve
      working-directory: .
    - name: Terraform Destroy
      id: destroy
      run: terraform destroy --auto-approve
      working-directory: .  
      

    
        
    
        
